### ISSUE TITLE
Meet some problem.

### ISSUE THREAD

**Issue by NeeMax** [Jacen789/NewsCrawler#1]
Traceback (most recent call last):
  File "D:/Jupyter/Code/Semester 2/NewsCrawler-master/main.py", line 18, in <module>
    news_crawler.save_news(sina_news_df, os.path.join(news_path, 'sina_latest_news.csv'))
  File "D:\Jupyter\Code\Semester 2\NewsCrawler-master\utils_fincrawler\news_crawler.py", line 177, in save_news
    news_df.to_csv(path, index=False, encoding='gb18030')
AttributeError: 'NoneType' object has no attribute 'to_csv'

Could you tell me how to solve it? 
Thank you!

**Comment by Jacen789** [comment]
It's possible that your IP is banned. So the value of news_df is None.
I haven't maintained the code for a long time. The structure and API of the web pages often change. It's may be the reason why you haven't crawled anything.
